"""
test_solvers.py
---------------
Test suite for Gil-Pelaez CDF inversion and quantile solvers.

Runs as a plain Python script (no pytest required), but is also
fully compatible with pytest when available.

Test groups
-----------
1. Integrand spot checks     — point values of cdf/pdf/d_pdf integrands
2. CDF structural properties — monotonicity, boundary behaviour, [0,1] range
3. PDF vs finite difference  — f(x) ≈ [F(x+ε) - F(x-ε)] / 2ε
4. Brent solver round-trips  — F(Q(p)) = p for p in (0,1)
5. Halley solver             — agrees with Brent to 1e-6
6. calculate_integral        — returns float, consistent with calculate_cdf
7. Edge cases                — invalid inputs raise cleanly

Reference values were generated by running with upper integration
limit = 20 000 and verified stable across quadrature configurations.

Author: Harsh Parikh
"""

import sys
import warnings
import numpy as np

from char_func import HestonParams
from solvers import (
    cdf_integrand,
    pdf_integrand,
    d_pdf_integrand,
    calculate_cdf,
    calculate_pdf,
    calculate_integral,
    run_brent_solver,
    run_halley_solver,
)

# ---------------------------------------------------------------------------
# Test runner
# ---------------------------------------------------------------------------

_results = {"passed": 0, "failed": 0}


def check(label: str, condition: bool, detail: str = "") -> bool:
    if condition:
        print(f"  ✅ {label}")
        _results["passed"] += 1
    else:
        print(f"  ❌ {label}  {detail}")
        _results["failed"] += 1
    return condition


def section(title: str):
    print(f"\n{'='*55}")
    print(f"  {title}")
    print(f"{'='*55}")


# ---------------------------------------------------------------------------
# Shared parameters
# ---------------------------------------------------------------------------

# Standard Heston parameters satisfying the Feller condition:
#   2κθ = 0.16 > σ² = 0.09  ✓
P = HestonParams(
    kappa=2.0,
    theta=0.04,
    sigma=0.3,
    v_t=0.04,
    v_u=0.04,
    dt=1.0 / 12.0,
)

MEAN_VAR = 0.5 * (P.v_t + P.v_u) * P.dt  # ≈ 0.003333


# ---------------------------------------------------------------------------
# 1. Integrand spot checks
# ---------------------------------------------------------------------------


def test_integrands():
    section("1. Integrand spot checks")

    # cdf_integrand at (mean, u=1)
    # Im(φ) is tiny for small dt, so value is near zero
    cdf_val = cdf_integrand(MEAN_VAR, 1.0, P)
    check(
        "cdf_integrand(mean, 1) ≈ -7.204e-6",
        abs(cdf_val - (-7.2037e-6)) < 1e-9,
        f"got {cdf_val:.6e}",
    )

    # pdf_integrand at (mean, u=1): φ≈1, cos(u·mean)≈1 → result ≈ 1/π
    pdf_val = pdf_integrand(MEAN_VAR, 1.0, P)
    check(
        "pdf_integrand(mean, 1) ≈ 1/π",
        abs(pdf_val - 1.0 / np.pi) < 1e-6,
        f"got {pdf_val:.8f}, expected {1/np.pi:.8f}",
    )

    # Identity at u=1: d_pdf_integrand = -cdf_integrand
    # (because d_pdf = (u/π)·Im[...] and cdf = -Im[...]/(uπ), so at u=1 they are negatives)
    dpdf_val = d_pdf_integrand(MEAN_VAR, 1.0, P)
    check(
        "d_pdf_integrand(mean,1) == -cdf_integrand(mean,1)  [at u=1]",
        abs(dpdf_val + cdf_val) < 1e-12,
        f"d_pdf={dpdf_val:.6e}, -cdf={-cdf_val:.6e}",
    )

    # Singularity guard u→0: cdf_integrand → x/π analytically
    x_test = 0.005
    sing_cdf = cdf_integrand(x_test, 1e-10, P)
    check(
        "cdf_integrand singularity u→0 returns x/π",
        abs(sing_cdf - x_test / np.pi) < 1e-10,
        f"got {sing_cdf:.8f}, expected {x_test/np.pi:.8f}",
    )

    # Singularity guard u→0: pdf_integrand → 1/π
    sing_pdf = pdf_integrand(x_test, 1e-10, P)
    check(
        "pdf_integrand singularity u→0 returns 1/π",
        abs(sing_pdf - 1.0 / np.pi) < 1e-10,
        f"got {sing_pdf:.8f}",
    )

    # All integrands finite across wide u range
    u_vals = [0.0, 1e-9, 0.1, 1.0, 10.0, 100.0, 1000.0]
    x_test = 0.003
    all_finite = all(
        np.isfinite(cdf_integrand(x_test, u, P))
        and np.isfinite(pdf_integrand(x_test, u, P))
        and np.isfinite(d_pdf_integrand(x_test, u, P))
        for u in u_vals
    )
    check("All integrands finite for u in [0, 1000]", all_finite)


# ---------------------------------------------------------------------------
# 2. CDF structural properties
# ---------------------------------------------------------------------------


def test_cdf():
    section("2. CDF structural properties")

    cdf_low = calculate_cdf(1e-3, P)
    check("F(0.001) < 0.01  [near-zero boundary]", cdf_low < 0.01, f"got {cdf_low:.6f}")

    cdf_high = calculate_cdf(0.008, P)
    check(
        "F(0.008) > 0.999  [near-one boundary]", cdf_high > 0.999, f"got {cdf_high:.6f}"
    )

    cdf_mid = calculate_cdf(MEAN_VAR, P)
    check(
        "0.3 < F(mean) < 0.7  [median near mean]",
        0.3 < cdf_mid < 0.7,
        f"got {cdf_mid:.4f}",
    )

    x_vals = [0.001, 0.002, 0.003, 0.0033, 0.004, 0.005, 0.006, 0.007]
    cdfs = [calculate_cdf(x, P) for x in x_vals]
    non_mono = [
        (x_vals[i], cdfs[i], cdfs[i + 1])
        for i in range(len(cdfs) - 1)
        if cdfs[i] >= cdfs[i + 1]
    ]
    check(
        "F strictly monotone increasing",
        len(non_mono) == 0,
        f"violated at: {non_mono}",
    )

    x_grid = np.linspace(0.001, 0.009, 20)
    out_of_range = [
        (x, calculate_cdf(x, P))
        for x in x_grid
        if not (-1e-4 <= calculate_cdf(x, P) <= 1 + 1e-4)
    ]
    check(
        "F(x) in [0,1] across support",
        len(out_of_range) == 0,
        f"violations: {out_of_range}",
    )

    # Pre-validated reference values
    references = [
        (0.0020, 0.000091, 5e-4, "F(0.002) ≈ 0.000091"),
        (0.0030, 0.199219, 5e-4, "F(0.003) ≈ 0.1992"),
        (0.0033, 0.461244, 5e-4, "F(0.0033) ≈ 0.4612"),
        (0.0040, 0.933225, 5e-4, "F(0.004) ≈ 0.9332"),
        (0.0050, 0.999785, 5e-4, "F(0.005) ≈ 0.9998"),
    ]
    for x, expected, tol, label in references:
        result = calculate_cdf(x, P)
        check(
            label,
            abs(result - expected) < tol,
            f"got {result:.6f}, expected {expected:.6f}",
        )


# ---------------------------------------------------------------------------
# 3. PDF vs finite difference
# ---------------------------------------------------------------------------


def test_pdf():
    section("3. PDF vs finite difference  [f(x) ≈ ΔF/Δx]")

    epsilon = 1e-5
    for x in [0.002, 0.003, 0.0033, 0.004, 0.005]:
        pdf_val = calculate_pdf(x, P)
        fd = (calculate_cdf(x + epsilon, P) - calculate_cdf(x - epsilon, P)) / (
            2 * epsilon
        )
        rel_err = abs(pdf_val - fd) / max(abs(fd), 1e-10)
        check(
            f"PDF({x:.4f}) matches FD to <1%",
            rel_err < 0.01,
            f"PDF={pdf_val:.4f}, FD={fd:.4f}, rel_err={rel_err:.2e}",
        )

    x_grid = np.linspace(0.001, 0.008, 30)
    neg = [(x, calculate_pdf(x, P)) for x in x_grid if calculate_pdf(x, P) < -1e-3]
    check("PDF(x) >= 0 across support", len(neg) == 0, f"negative at: {neg}")


# ---------------------------------------------------------------------------
# 4. Brent solver
# ---------------------------------------------------------------------------


def test_brent():
    section("4. Brent solver:  F(Q(p)) = p")

    probs = [0.05, 0.10, 0.25, 0.50, 0.75, 0.90, 0.95]

    for var in probs:
        x_star = run_brent_solver(var, P)
        err = abs(calculate_cdf(x_star, P) - var)
        check(f"Brent round-trip p={var}", err < 1e-5, f"err={err:.2e}")

    quantiles = [run_brent_solver(p, P) for p in probs]
    check(
        "Brent quantiles strictly monotone",
        all(quantiles[i] < quantiles[i + 1] for i in range(len(quantiles) - 1)),
    )

    check("All Brent quantiles > 0", all(q > 0 for q in quantiles))

    references = [
        (0.10, 0.0028325373, "Q(0.10)"),
        (0.25, 0.0030667028, "Q(0.25)"),
        (0.50, 0.0033403547, "Q(0.50)"),
        (0.75, 0.0036282090, "Q(0.75)"),
        (0.90, 0.0038994546, "Q(0.90)"),
    ]
    for var, expected, label in references:
        result = run_brent_solver(var, P)
        check(
            f"Brent {label} matches reference",
            abs(result - expected) < 1e-6,
            f"got {result:.10f}, expected {expected:.10f}",
        )

    for bad in [0.0, 1.0, -0.1, 1.1]:
        try:
            run_brent_solver(bad, P)
            check(
                f"Brent raises ValueError for var={bad}", False, "no exception raised"
            )
        except ValueError:
            check(f"Brent raises ValueError for var={bad}", True)
        except Exception as e:
            check(
                f"Brent raises ValueError for var={bad}",
                False,
                f"got {type(e).__name__}",
            )


# ---------------------------------------------------------------------------
# 5. Halley solver
# ---------------------------------------------------------------------------


def test_halley():
    section("5. Halley solver:  agrees with Brent to 1e-6")

    for var in [0.10, 0.25, 0.50, 0.75, 0.90]:
        x_halley = run_halley_solver(var, P)
        x_brent = run_brent_solver(var, P)
        diff = abs(x_halley - x_brent)
        check(
            f"Halley ≈ Brent at p={var}",
            diff < 1e-6,
            f"diff={diff:.2e}",
        )

    for var in [0.10, 0.50, 0.90]:
        x_star = run_halley_solver(var, P)
        err = abs(calculate_cdf(x_star, P) - var)
        check(f"Halley round-trip p={var}", err < 1e-5, f"err={err:.2e}")

    for bad in [0.0, 1.0]:
        try:
            run_halley_solver(bad, P)
            check(
                f"Halley raises ValueError for var={bad}", False, "no exception raised"
            )
        except ValueError:
            check(f"Halley raises ValueError for var={bad}", True)
        except Exception as e:
            check(
                f"Halley raises ValueError for var={bad}",
                False,
                f"got {type(e).__name__}",
            )


# ---------------------------------------------------------------------------
# 6. calculate_integral interface
# ---------------------------------------------------------------------------


def test_calculate_integral():
    section("6. calculate_integral interface")

    result = calculate_integral(pdf_integrand, MEAN_VAR, P)

    check(
        "calculate_integral returns float",
        isinstance(result, float),
        f"got {type(result)}",
    )
    check("PDF integral > 0 at mean", result > 0, f"got {result}")

    integral = calculate_integral(cdf_integrand, MEAN_VAR, P)
    direct = calculate_cdf(MEAN_VAR, P)
    check(
        "calculate_cdf == 0.5 + calculate_integral(cdf_integrand)",
        abs((0.5 + integral) - direct) < 1e-10,
        f"0.5+integral={0.5+integral:.10f}, direct={direct:.10f}",
    )


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    print(
        f"\nHeston params: κ={P.kappa}, θ={P.theta}, σ={P.sigma}, "
        f"V_t={P.v_t}, V_u={P.v_u}, Δt={P.dt:.4f}"
    )
    print(
        f"Feller condition: 2κθ={2*P.kappa*P.theta:.3f} > σ²={P.sigma**2:.3f}  "
        f"{'✅' if 2*P.kappa*P.theta > P.sigma**2 else '❌'}"
    )

    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        # test_integrands()
        # test_cdf()
        # test_pdf()
        # test_brent()
        # test_halley()
        test_calculate_integral()

    total = _results["passed"] + _results["failed"]
    print(f"\n{'='*55}")
    print(f"  {_results['passed']}/{total} passed   |   {_results['failed']} failed")
    print(f"{'='*55}\n")
    sys.exit(0 if _results["failed"] == 0 else 1)
